# Generated by Django 5.2.6 on 2025-09-21 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="auth_status",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="user_role",
        ),
        migrations.AlterField(
            model_name="codeverified",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("948ac378-a9f1-41c3-a44f-eba5fa9f9fb2"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("948ac378-a9f1-41c3-a44f-eba5fa9f9fb2"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
