# Generated by Django 5.2.6 on 2025-09-20 13:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codeverified",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("530f548f-e677-4bd3-ac58-784cd8a6cc02"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.UUIDField(
                default=uuid.UUID("530f548f-e677-4bd3-ac58-784cd8a6cc02"),
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
